#!/bin/sh

### Homebrew Cask apps
brew_cask_expand_alias() {
  brew cask info "$1" 2>/dev/null | head -1 | awk '{gsub(/:/, ""); print $1}'
}

brew_cask_is_installed() {
  local name="$(brew_cask_expand_alias "$1")"

  brew cask list -1 | grep -Fqx "$name"
}

brew_cask_install() {
  if brew_cask_is_installed "$1"; then
    fancy_echo "%s is already installed . Skipping ..." "$1"
  else
    fancy_echo "Installing %s ..." "$1"
    brew cask install "$@"
  fi
}

fancy_echo "Checking Cask apps ..."

brew_install_or_upgrade 'caskroom/cask/brew-cask'

brew_tap 'caskroom/versions'
brew_tap 'caskroom/fonts'

# Dev tools
brew_cask_install 'java'
brew_cask_install 'scala'

# Native apps
brew_cask_install 'iterm2'
brew_cask_install 'macvim'
brew_cask_install 'sublime-text-3'
brew_cask_install 'atom'
brew_cask_install 'mou'
brew_cask_install 'amethyst'
brew_cask_install 'virtualbox'
brew_cask_install 'vagrant'
brew_cask_install 'sequel-pro'
brew_cask_install 'firefox'
brew_cask_install 'google-chrome'
brew_cask_install 'google-chrome-canary'

# Quicklook plugins
brew_cask_install 'betterzipql'
brew_cask_install 'qlcolorcode'
brew_cask_install 'qlimagesize'
brew_cask_install 'qlmarkdown'
brew_cask_install 'qlstephen'
brew_cask_install 'quicklook-json'
brew_cask_install 'qlprettypatch'
brew_cask_install 'quicklook-csv'

# Open-source Fonts
brew_cask_install 'font-meslo-lg'
brew_cask_install 'font-meslo-lg-for-powerline'
brew_cask_install 'font-source-code-pro'
brew_cask_install 'font-source-code-pro-for-powerline'
brew_cask_install 'font-source-sans-pro'
brew_cask_install 'font-ubuntu'
