#!/bin/sh

# Desktop apps and plugins
fancy_echo "Checking Desktop apps ..."

brew bundle --file=- <<EOF
tap "caskroom/versions"

# Keyboard
cask "karabiner-elements"

# Quicklook plugins
cask "betterzipql"
cask "qlcolorcode"
cask "qlimagesize"
cask "qlmarkdown"
cask "qlstephen"
cask "quicklook-json"
cask "qlprettypatch"
cask "quicklook-csv"

EOF
