#!/bin/sh

vscode_is_installed() {
  code --list-extensions | grep -iFq "$1"
}

vscode_install() {
  if vscode_is_installed "$1"; then
    fancy_echo "[VSCode] %s is already installed . Skipping ..." "$1"
  else
    fancy_echo "[VSCode] Installing %s ..." "$1"
    code --install-extension "$@"
  fi
}

fancy_echo "Installing Development tools ..."

brew bundle --file=- <<EOF

tap "homebrew/cask-fonts"

## Languages
brew "java"
brew "python3"
brew "go"

# Dev tools
cask "iterm2"
cask "visual-studio-code"
brew "neovim"
cask "docker"
brew "docker-compose"
brew "flake8"
brew "black"
cask "mitmproxy"

# Data Science tools
brew "ipython"
brew "pipenv"
cask "anaconda"

# Shell
brew "git-extras"
brew "tig"
brew "shellcheck"
brew "diff-so-fancy"
brew "git-delta"
brew "tldr"
brew "awscli"

# Fonts
cask "font-fira-code"
cask "font-fira-code-nerd-font"
cask "font-fira-mono"
cask "font-fira-mono-nerd-font"
cask "font-meslo-lg"
cask "font-meslo-lg-nerd-font"
cask "font-source-code-pro"
cask "font-ubuntu"

EOF

fancy_echo "Updating VSCode packages ..."

vscode_install "Gruntfuggly.todo-tree"
vscode_install "ms-python.isort"
vscode_install "ms-vscode-remote.remote-containers" 
vscode_install "ms-azuretools.vscode-docker"
vscode_install "GrapeCity.gc-excelviewer"
vscode_install "GitHub.vscode-pull-request-github"
vscode_install "eamodio.gitlens"
vscode_install "VisualStudioExptTeam.vscodeintellicode"
vscode_install "ms-kubernetes-tools.vscode-kubernetes-tools"
vscode_install "DavidAnson.vscode-markdownlint"
vscode_install "christian-kohler.path-intellisense"
vscode_install "esbenp.prettier-vscode"
vscode_install "ms-python.python"
vscode_install "timonwong.shellcheck"
vscode_install "vscodevim.vim"
vscode_install "redhat.vscode-yaml"

# Themes and icons
vscode_install "Equinusocio.vsc-material-theme"
vscode_install "Equinusocio.vsc-material-theme-icons"
vscode_install "monokai.theme-monokai-pro-vscode"

