#!/bin/sh

# Atom packages
apm_is_installed() {
  apm list | grep -iFq "$1"
}

apm_install() {
  if apm_is_installed "$1"; then
    fancy_echo "[Atom] %s is already installed . Skipping ..." "$1"
  else
    fancy_echo "[Atom] Installing %s ..." "$1"
    apm install "$@"
  fi
}

fancy_echo "Updating Atom packages ..."

apm update -c false

apm_install 'vim-mode'
apm_install 'jumpy'
apm_install 'key-peek'
apm_install 'symbols-tree-view'
apm_install 'block-travel'
apm_install 'highlight-selected'
apm_install 'emmet'
apm_install 'docblockr'

apm_install 'file-icons'
apm_install 'project-colorize'
apm_install 'advanced-new-file'
apm_install 'project-manager'
apm_install 'whitespace'

apm_install 'color-picker'
apm_install 'pigments'
apm_install 'todo-show'
apm_install 'ask-stack'
apm_install 'markdown-preview'
apm_install 'zen'
apm_install 'git-history'
apm_install 'merge-conflicts'

apm_install 'autocomplete-plus'
apm_install 'autocomplete-paths'
apm_install 'autocomplete-emojis'
apm_install 'autocomplete-plus-python-jedi'
apm_install 'atom-ternjs'
apm_install 'autocomplete-html'
apm_install 'autocomplete-css'

apm_install 'linter'
apm_install 'linter-flake8'
apm_install 'linter-pep257'
apm_install 'linter-rubocop'
apm_install 'linter-clojure'
apm_install 'linter-scalac'
apm_install 'linter-shellcheck'
apm_install 'linter-jshint'
apm_install 'linter-coffeelint'
apm_install 'linter-csslint'
apm_install 'linter-scss-lint'
apm_install 'atom-beautify'

apm_install 'minimap'
apm_install 'minimap-git-diff'
apm_install 'minimap-selection'
apm_install 'minimap-find-and-replace'
apm_install 'minimap-highlight-selected'
apm_install 'minimap-bookmarks'

# Atom packages dependencies
fancy_echo "Updating Atom packages dependencies ..."

pip_install_or_update 'flake8'
pip_install_or_update 'pep257'
pip_install_or_update 'jedi'

npm install -g jshint
npm install -g coffeelint
npm install -g csslint

brew_install_or_upgrade 'shellcheck'

gem_install_or_update 'rubocop'
gem_install_or_update 'scss_lint'
