#!/bin/sh

fancy_echo "Checking command-line packages ..."

brew bundle --file=- <<EOF

# Install GNU find, locate, updatedb, and xargs, g-prefixed.
brew "findutils"
brew "gnu-sed"

brew "coreutils"
brew "curl"
brew "httpie"
brew "jq"
brew "fd"
brew "lsd"
brew "bat"
brew "dust"
brew "zoxide"
brew "fzf"

brew "gpg"
brew "ssh-copy-id"
brew "mitmproxy"
brew "pv"
brew "trash"
brew "p7zip"
brew "glances"
brew "zsh-syntax-highlighting"
brew "youtube-dl"

EOF
