#!/bin/sh
pip_is_installed() {
  pip list 2> /dev/null | grep -q "$1"
}

pip_install_or_update() {
  if pip_is_installed "$1"; then
    fancy_echo "[Pip] %s is already installed . Updating ..." "$1"
    pip install --upgrade "$@"
  else
    fancy_echo "[Pip] Installing %s ..." "$1"
    pip install "$@"
  fi
}

append_luarocks() {
  local text='rocks_servers = { "http://rocks.moonscript.org" }'
  local luarocks="/usr/local/etc/luarocks52/config-5.2.lua"

  if ! grep -Fqs "$text" "$luarocks"; then
      printf "\n%s\n" "$text" >> "$luarocks"
  fi
}

fancy_echo "Checking misc tools ..."

# JS tools
npm install -g yo
npm install -g bower
npm install -g grunt-cli
npm install -g gulp

# Pip tools
pip_install_or_update 'virtualenvwrapper'

# Brew tools
brew_install_or_upgrade 'leiningen'

# Mjolnir
append_luarocks

luarocks install mjolnir.hotkey
luarocks install mjolnir.application
luarocks install mjolnir.tiling
luarocks install mjolnir.th.hints

